import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  

// Super admin
{
  path: '/su/dashboard',
  title: 'MENUITEMS.HOME.TEXT',
  moduleName: 'dashboard',
  iconType: 'material-icons-two-tone',
  icon: 'dashboard',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['1'],
  submenu: [],
},

{
  path: '/su/user/user-list',
  title: 'MENUITEMS.USER.TEXT',
  moduleName: 'user',
  iconType: 'material-icons-two-tone',
  icon: 'person',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['1'],
  submenu: [],
},

  // 3 Modules

  {
    path: '/admin/dashboard/main',
    title: 'MENUITEMS.HOME.TEXT',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [],
  },
  // {
  //   path: '',
  //   title: 'MENUITEMS.STUDENTS.TEXT',
  //   moduleName: 'students',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'people_alt',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['3'],
  //   submenu: [
  //     {
  //       path: '/admin/students/add-student',
  //       title: 'MENUITEMS.STUDENTS.LIST.ADD-STUDENT',
  //       moduleName: 'students',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/admin/students/all-students',
  //       title: 'MENUITEMS.STUDENTS.LIST.ALL-STUDENTS',
  //       moduleName: 'students',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: '',
    title: 'MENUITEMS.LICENSE.TEXT',
    moduleName: 'license',
    iconType: 'material-icons-two-tone',
    icon: 'picture_in_picture',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [
      {
        path: '/admin/license/license-list',
        title: 'MENUITEMS.LICENSE.LIST.ALL-LICENSE',
        moduleName: 'license',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/license/add-license',
        title: 'MENUITEMS.LICENSE.LIST.ADD-LICENSE',
        moduleName: 'license',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.PACKAGE.TEXT',
    moduleName: 'package',
    iconType: 'material-icons-two-tone',
    icon: 'view_compact',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [
      {
        path: '/admin/package/package-list',
        title: 'MENUITEMS.PACKAGE.LIST.ALL-PACKAGE',
        moduleName: 'package',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/package/add-package',
        title: 'MENUITEMS.PACKAGE.LIST.ADD-PACKAGE',
        moduleName: 'package',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  // {
  //   path: '',
  //   title: 'MENUITEMS.PRE-REQUISITE.TEXT',
  //   moduleName: 'pre-requisite',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'picture_in_picture',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['3'],
  //   submenu: [
  //     {
  //       path: '/admin/pre-requisite/pre-requisite-list',
  //       title: 'MENUITEMS.PRE-REQUISITE.LIST.ALL-PRE-REQUISITE',
  //       moduleName: 'pre-requisite',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/admin/pre-requisite/add-pre-requisite',
  //       title: 'MENUITEMS.PRE-REQUISITE.LIST.ADD-PRE-REQUISITE',
  //       moduleName: 'pre-requisite',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: '/admin/employee/employee-list',
    title: 'MENUITEMS.EMPLOYEE.TEXT',
    moduleName: 'employee',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [],
  },

  // {
  //   path: '/admin/schedule/schedule-list',
  //   title: 'MENUITEMS.SCHEDULE.TEXT',
  //   moduleName: 'schedule',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'event_note',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['3'],
  //   submenu: [],
  // },
  {
    path: '/admin/time/add-time',
    title: 'MENUITEMS.TIME.TEXT',
    moduleName: 'time',
    iconType: 'material-icons-two-tone',
    icon: 'av_timer',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [],
  },
  {
    path: '/admin/retest/retest-payment-list',
    title: 'MENUITEMS.RETEST.TEXT',
    moduleName: 'retest',
    iconType: 'material-icons-two-tone',
    icon: 'payment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [],
  },
  {
    path: '/admin/refund/refund-list',
    title: 'MENUITEMS.REFUND.TEXT',
    moduleName: 'refund',
    iconType: 'material-icons-two-tone',
    icon: 'payment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [],
  },
  {
    path: '/admin/message',
    title: 'MENUITEMS.MESSAGE-TEMPLATE.TEXT',
    moduleName: 'message',
    iconType: 'material-icons-two-tone',
    icon: 'message',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.REPORTS.TEXT',
    moduleName: 'reports',
    iconType: 'material-icons-two-tone',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['3'],
    submenu: [
      {
        path: '/admin/reports/revenue-report',
        title: 'MENUITEMS.REPORTS.LIST.REVENUE-REPORT',
        moduleName: 'reports',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/reports/registration-report',
        title: 'MENUITEMS.REPORTS.LIST.REGISTRATION-REPORT',
        moduleName: 'reports',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  {
    path: '/pages/view-schedule',
    title: 'MENUITEMS.SCHEDULE.TEXT',
    moduleName: 'schedule',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['5'],
    submenu: [],
  },
  {
    path: '/pages/students/view',
    title: 'MENUITEMS.STUDENTS.TEXT',
    moduleName: 'students',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: '',
    groupTitle: false, 
    badge: '',
    badgeClass: '',
    role: ['5'],
    submenu: [],
  },
  {
    path: '/pages/timeline',
    title: 'MENUITEMS.TIMELINE.TEXT',
    moduleName: 'timeline',
    iconType: 'material-icons-two-tone', 
    icon: 'timeline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['5'],
    submenu: [],
  },

  {
    path: '/pages/view-schedule',
    title: 'MENUITEMS.SCHEDULE.TEXT',
    moduleName: 'schedule',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['6'],
    submenu: [],
  },
  {
    path: '/pages/students/view',
    title: 'MENUITEMS.STUDENTS.TEXT',
    moduleName: 'students',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: '',
    groupTitle: false, 
    badge: '',
    badgeClass: '',
    role: ['6'],
    submenu: [],
  },


  {
    path: '',
    title: 'MENUITEMS.STUDENTS.TEXT',
    moduleName: 'students',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [
      {
        path: '/clerk/students/add-student',
        title: 'MENUITEMS.STUDENTS.LIST.ADD-STUDENT',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/clerk/students/all-students',
        title: 'MENUITEMS.STUDENTS.LIST.ALL-STUDENTS',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '/clerk/schedule/schedule-list',
    title: 'MENUITEMS.SCHEDULE.TEXT',
    moduleName: 'schedule',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },
  {
    path: '/clerk/apply/license',
    title: 'MENUITEMS.APPLY.TEXT',
    moduleName: 'apply',
    iconType: 'material-icons-two-tone', 
    icon: 'picture_in_picture',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },

  {
    path: '/clerk/student-schedule/schedule-list',
    title: 'MENUITEMS.SCHEDULE.STUD-TEXT',
    moduleName: 'schedule',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },
  {
    path: '/clerk/license-process/license-process',
    title: 'MENUITEMS.LICENSE-PROCESS.TEXT',
    moduleName: 'license',
    iconType: 'material-icons-two-tone', 
    icon: 'picture_in_picture',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },

  {
    path: '/clerk/refund/refund-process',
    title: 'MENUITEMS.REFUND-PROCESS.TEXT',
    moduleName: 'refund',
    iconType: 'material-icons-two-tone', 
    icon: 'payment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },

  {
    path: '/clerk/renewal/renewal-process',
    title: 'MENUITEMS.RENEWAL-PROCESS.TEXT',
    moduleName: 'renewal',
    iconType: 'material-icons-two-tone', 
    icon: 'payment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },


  {
    path: '/Track',
    title: 'MENUITEMS.TIMELINE.TEXT',
    moduleName: 'timeline',
    iconType: 'material-icons-two-tone', 
    icon: 'timeline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },

  // {
  //   path: '/clerk/GDL/Gdl-apply-license',
  //   title: 'MENUITEMS.GDL-APPLY-LICENSE.TEXT',
  //   moduleName: 'license',
  //   iconType: 'material-icons-two-tone', 
  //   icon: 'picture_in_picture',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['4'],
  //   submenu: [],
  // },
  
  // {
  //   path: '/clerk/reports/sales-report',
  //   title: 'MENUITEMS.REPORTS.LIST.SALES-REPORT',
  //   moduleName: 'reports',
  //   iconType: 'material-icons-two-tone', 
  //   icon: 'description',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['4'],
  //   submenu: [],
  // },
  {
    path: '/clerk/reports/pending-report',
    title: 'MENUITEMS.REPORTS.LIST.PENDING-REPORT',
    moduleName: 'reports',
    iconType: 'material-icons-two-tone', 
    icon: 'description',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },
  {
    path: '/clerk/reports/pending-schedule',
    title: 'MENUITEMS.REPORTS.LIST.PENDING-SCHEDULE',
    moduleName: 'reports',
    iconType: 'material-icons-two-tone', 
    icon: 'description',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },
  {
    path: '/clerk/generate/lform',
    title: 'MENUITEMS.GENERATE-FORM.TEXT',
    moduleName: 'generate',
    iconType: 'material-icons-two-tone', 
    icon: 'description',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['4'],
    submenu: [],
  },
 
]
